config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  namespace :admin do
    resources :users
  end

  resources :hobbies do
    member do
      post :move_up
      post :move_down
    end
  end
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  validates :title, presence: true

    has_many :hobbyships
    has_many :users, :through => :hobbyships

    mount_uploader :image, ImageUploader

    acts_as_list
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @hobbies = Hobby.all.order('position ASC')
  end

  def show
    @hobby = Hobby.find(params[:id])
  end

  def new
    @hobby = Hobby.new
  end

  def create
    @hobby = Hobby.new(hobby_params)

    if @hobby.save
      redirect_to hobbies_path
    else
      render :new
    end
  end

  def edit
    @hobby = Hobby.find(params[:id])
  end

  def update
    @hobby = Hobby.find(params[:id])
    if @hobby.update(hobby_params)
      redirect_to hobbies_path
    else
      render :edit
    end
  end

  def destroy
    @hobby = Hobby.find(params[:id])

    @hobby.destroy

    redirect_to hobbies_path
  end

  def move_up
    @hobby = Hobby.find(params[:id])
    @hobby.move_higher
    redirect_to hobbies_path
  end

  def move_down
    @hobby = Hobby.find(params[:id])
    @hobby.move_lower
    redirect_to hobbies_path
  end

  private

  def hobby_params
    params.require(:hobby).permit(:title, :image, :popular_time, :description)
  end

end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/views/hobbies/_form.html.erb
<%= simple_form_for @hobby do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :popular_time, :as => :string %>
<%= f.input :image, as: :file %>
<%= f.submit "Submit" %>
<% end %>

<script>
 $("#hobby_popular_time").datepicker({ format: "yyyy/mm/dd" });
 autosize($("#hobby_description"))
</script>

app/views/hobbies/edit.html.erb
<h1> Edit a hobby </h1>

<%= render "form"%>

app/views/hobbies/index.html.erb
<div class="pull-right">
  <%= link_to("Add a hobby", new_hobby_path, :class => "btn btn-default" ) %>
</div>
<table class="table table-boldered">
  <% @hobbies.each do |hobby| %>
  <tr>
    <td>
      <%= link_to(hobby.title, hobby_path(hobby)) %>
    </td>
    <td>
      <% if hobby.image.present? %>
          <%= image_tag(hobby.image.thumb.url, class: "thumbnail") %>
      <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
      <% end %>
    </td>
    <td>
      <%= link_to("Up", move_up_hobby_path(hobby), :method => :post) %>
      |
      <%= link_to("Down", move_down_hobby_path(hobby), :method => :post) %>
      |
      <%= link_to("Destroy", hobby_path(hobby), :method => :delete, :data => { :confirm => "Are you sure?" }) %>
    </td>
    <td>
      <%= hobby.created_at %>
    </td>
  </tr>
  <% end %>
</table>

app/views/hobbies/new.html.erb
<h1> Add a hobby </h1>

<%= render "form"%>

app/views/hobbies/show.html.erb
<%= link_to("Edit", edit_hobby_path(@hobby)) %>

<h1> <%= @hobby.title %> </h1>
<div class="col-md-6">
    <% if @hobby.image.present? %>
      <%= image_tag(@hobby.image.medium.url, class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
</div>