config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  namespace :admin do
    resources :users
  end

  resources :hobbies do
    member do
      post :move_up
      post :move_down
    end
  end
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017
        <br>Design by
        <a href="https://www.linkedin.com/in/wei-yang-9102bb23/" target=_new>WeiYang</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
              data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="/">Skeleton</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse" id="bs-example-navbar-collapse-1" aria-expanded="false">
            <ul class="nav navbar-nav navbar-right">
                <li>
                  <% if !current_user %>
                    <li><%= link_to(content_tag(:i, "注册", class: 'fa fa-user-o'), new_user_registration_path) %> </li>
                    <li><%= link_to(content_tag(:i, "登录", class: 'fa fa-sign-in'), new_user_session_path) %></li>
                  <% else %>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.nickname %>
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <% if current_user.is_admin? %>
                          <li><%= link_to(content_tag(:i, "管理界面", class: 'fa fa-info-circle'), admin_users_path) %></li>
                        <% end %>
                        <li><%= link_to(content_tag(:i, "修改", class: 'fa fa-user-circle'), edit_registration_path(:user)) %></li>
                        <li><%= link_to(content_tag(:i, "退出", class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %></li>
                      </ul>
                    </li>
                  <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>