config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  namespace :admin do
    resources :users
  end

  resources :hobbies do
    member do
      post :move_up
      post :move_down
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSkeleton</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
            <li class="active"><%= link_to("Users", admin_users_path ) %> </li>
            <li class="active"><%= link_to("Hobbies", hobbies_path ) %> </li>
          </ul>
        </div>
        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>

    <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSkeleton</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>

    <%= render "common/footer" %>
  </body>
</html>